/* 
 * My Title
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.ApiClient.Client;
using IO.ApiClient.Api;
using IO.ApiClient.Model;

namespace IO.ApiClient.Test
{
    /// <summary>
    ///  Class for testing OrdersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class OrdersApiTests
    {
        private OrdersApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new OrdersApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrdersApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' OrdersApi
            //Assert.IsInstanceOfType(typeof(OrdersApi), instance, "instance is a OrdersApi");
        }

        
        /// <summary>
        /// Test OrdersGet
        /// </summary>
        [Test]
        public void OrdersGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.OrdersGet();
            //Assert.IsInstanceOf<List<Order>> (response, "response is List<Order>");
        }
        
        /// <summary>
        /// Test OrdersGetHistory
        /// </summary>
        [Test]
        public void OrdersGetHistoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.OrdersGetHistory();
            //Assert.IsInstanceOf<List<Trade>> (response, "response is List<Trade>");
        }
        
        /// <summary>
        /// Test OrdersPost
        /// </summary>
        [Test]
        public void OrdersPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Order order = null;
            //var response = instance.OrdersPost(order);
            //Assert.IsInstanceOf<Order> (response, "response is Order");
        }
        
        /// <summary>
        /// Test OrdersPostHistory
        /// </summary>
        [Test]
        public void OrdersPostHistoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Trade trade = null;
            //var response = instance.OrdersPostHistory(trade);
            //Assert.IsInstanceOf<Trade> (response, "response is Trade");
        }
        
    }

}
