/* 
 * My Title
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.ApiClient.Api;
using IO.ApiClient.Model;
using IO.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.ApiClient.Test
{
    /// <summary>
    ///  Class for testing SideEnum
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SideEnumTests
    {
        // TODO uncomment below to declare an instance variable for SideEnum
        //private SideEnum instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SideEnum
            //instance = new SideEnum();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SideEnum
        /// </summary>
        [Test]
        public void SideEnumInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SideEnum
            //Assert.IsInstanceOfType<SideEnum> (instance, "variable 'instance' is a SideEnum");
        }



    }

}
