/* 
 * My Title
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.ApiClient.Api;
using IO.ApiClient.Model;
using IO.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.ApiClient.Test
{
    /// <summary>
    ///  Class for testing Trade
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TradeTests
    {
        // TODO uncomment below to declare an instance variable for Trade
        //private Trade instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Trade
            //instance = new Trade();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Trade
        /// </summary>
        [Test]
        public void TradeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Trade
            //Assert.IsInstanceOfType<Trade> (instance, "variable 'instance' is a Trade");
        }


        /// <summary>
        /// Test the property 'BuyUserId'
        /// </summary>
        [Test]
        public void BuyUserIdTest()
        {
            // TODO unit test for the property 'BuyUserId'
        }
        /// <summary>
        /// Test the property 'SellUserId'
        /// </summary>
        [Test]
        public void SellUserIdTest()
        {
            // TODO unit test for the property 'SellUserId'
        }
        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Test]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }
        /// <summary>
        /// Test the property 'TradeQuantity'
        /// </summary>
        [Test]
        public void TradeQuantityTest()
        {
            // TODO unit test for the property 'TradeQuantity'
        }
        /// <summary>
        /// Test the property 'TradePrice'
        /// </summary>
        [Test]
        public void TradePriceTest()
        {
            // TODO unit test for the property 'TradePrice'
        }

    }

}
