/* 
 * My Title
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.ApiClient.Client.SwaggerDateConverter;

namespace IO.ApiClient.Model
{
    /// <summary>
    /// Defines SideEnum
    /// </summary>
    
    //[JsonConverter(typeof(StringEnumConverter))]
    
    public enum SideEnum
    {

        /// <summary>
        /// Enum Buy for value: Buy
        /// </summary>
        [EnumMember(Value = "Buy")]
        Buy = 1,

        /// <summary>
        /// Enum Sell for value: Sell
        /// </summary>
        [EnumMember(Value = "Sell")]
        Sell = 2
    }

}
